### ISSUE TITLE
Add Filter Functionality

### ISSUE THREAD

**Issue by squeekyfoot** [DivideBySara/codefellowsportfolio#7]
https://github.com/DivideBySara/codefellowsportfolio/blob/master/index.html#L67
and
https://github.com/DivideBySara/codefellowsportfolio/blob/master/scripts/pageView.js#L22

The category filter should have some functionality since it's on the master branch. Add a function to populate this list so that it could show only the categories selected.

**Comment by DivideBySara** [comment]
The category filter now populates. Thanks, SqueekyFoot!
